# Congressional Guide Docker Composer File
version: '2'
services:
  app:
    build: ./app
    image: acttaiwan/cgapp
    container_name: cgapp
    ports:
    - "49170:3000"
    volumes:
    # mount the db volume for db.sqlite3
    - ./db:/opt/db